name: masterevent
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Official Flutter localization support
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.0.3
  flutter_local_notifications: ^19.0.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  share_plus: ^10.1.4
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.3
  timezone: ^0.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Boldnose
      fonts:
        - asset: fonts/Boldnose-Regular.ttf
